services:
  nx-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nx-monorepo
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "${ANGULAR_PORT:-4200}:4200"  # Format is "HOST_PORT:CONTAINER_PORT"
      - "${NESTJS_PORT:-3333}:3000"   # Format is "HOST_PORT:CONTAINER_PORT"
      - "9229:9229"  # for Node.js debugging
    command: nx run-many --target=serve --projects=sandbox,api --parallel
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    env_file:
      - .env
    networks:
      - app-network

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
